### ISSUE TITLE
bug in find

### ISSUE THREAD

**Issue by solotim** [ericcurtin/CurtineIncSw.vim#6]
`let cmd="find . " . dirname . " -type f -iname " . t:IncSw . " | head -n1 | tr -d '\n'"`

should  be

`let cmd="find " . dirname . " -type f -iname " . t:IncSw . " | head -n1 | tr -d '\n'"`

**Comment by ericcurtin** [comment]
It's actually intentional to search from two directories. When I first wrote this I assumed that you opened vim from the base of your repo and that your repo contained both the implementation and the header files. Then I updated to search from both the current directory (pwd) and from the directory where the file you opened is (dirname in the vimscript) as a result of #5 

Closing... If you explain the issue you are seeing I will consider reopening... :+1: 

`head -n1` is a performance things that tells the find to stop executing once we found the first result. I assume the first result is the correct one (that's a best guess, but fine for my needs at least)

**Comment by solotim** [comment]
Well, the "assumption" you give may not be true for many vim users. For me, I open vim in my project root, where I have .vimrc and many setup for this project, then I have ag/ctrlp to navigate the whole project. If "find" the ".", it's a disaster for super large project. So I changed that for my use scenario. And I really think you need to think about this.

I made other changes as well. Specificially, when matching header, why do you use to escape back slash? 
And, I commented out the "shortcut" of # because if you open an unrelated file in between header and cpp, the # will be wrong.

```
function! FindInc()
  let dirname=fnamemodify(expand("%:p"), ":h")
  let cmd="find " . dirname . " -type f -iname " . t:IncSw . " | head -n1 | tr -d '\n'"

  let findRes=system(cmd)

  exe "e " findRes
endfun

function! CurtineIncSw()
"  if exists("t:IncSw")
"    e#
"    return 0
"  endif

  if match(expand("%"), '\.c') > 0
    let t:IncSw=substitute(expand("%:t"), '\.c\(.*\)', '.h*', "")
  elseif match(expand("%"), "\.h") > 0
    let t:IncSw=substitute(expand("%:t"), '\.h\(.*\)', '.c*', "")
  else
    return 0
  endif

  call FindInc()
endfun

~

```

**Comment by ericcurtin** [comment]
We removed the:

```
if exists("t:IncSw")
  e#
  return 0
endif
```

as part of #8

optimization, the only problem is that helps in really large projects such as yours. Would consider adding a similar optimization again. Would like to avoid having to search for the "switched from" file seeing as we already know where it is since we switched from there.
